meta_product_name: "bubbleheart"
meta_title: "bubbleheart - Find your next Bubble Tea obsession"
meta_description: "Never be without bubble tea again! Search for and rate local bubble tea shops."
meta_image: "cover.png" # should exist in `app/assets/images/`
